config/routes.rb
Rails.application.routes.draw do
  resources :open_studios, :only => [:show, :new, :create]
  resources :open_houses, :only => [:show, :new, :create]
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :reviews, :except => [:destroy, :new, :create]
  resources :categories, :only => [:show]
  resources :abstract_docs, :except => [:destroy, :index]
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


  get "abstract" => "pages#abstract"
  get ":slug" => "pages#show", :as => 'page'

  root "pages#show", slug: "home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/abstract_doc.rb
class AbstractDoc < ApplicationRecord
  belongs_to :category
  belongs_to :user
  resourcify
  has_many :reviews
  has_many :reviewers, through: :reviews, source: :user

  extend SimplestStatus

  statuses :draft, :submitted, :archived, :accepted

  mount_uploader :attachment, AttachmentUploader

  def status_enum
    AbstractDoc.statuses.for_select
  end

  after_save do
    NotificationsMailer.abstract_ack(self).deliver_now if self.submitted?
    NotificationsMailer.send_abstract(self).deliver_now if self.submitted?
  end
end

app/controllers/abstract_docs_controller.rb
class AbstractDocsController < ApplicationController
  before_action :set_abstract_doc, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_viewer, only: [:show]

  before_action :authenticate_editor, only: [:edit, :update, :destroy]
  # GET /abstract_docs
  # GET /abstract_docs.json
  def index
    @abstract_docs = AbstractDoc.where(user_id: current_user.id)
  end

  # GET /abstract_docs/1
  # GET /abstract_docs/1.json
  def show
  end

  # GET /abstract_docs/new
  def new
    @abstract_doc = AbstractDoc.new
  end

  # GET /abstract_docs/1/edit
  def edit
  end

  # POST /abstract_docs
  # POST /abstract_docs.json
  def create
    @abstract_doc = AbstractDoc.new(abstract_doc_params)
    @abstract_doc.user_id = current_user.id
    respond_to do |format|
      if @abstract_doc.save
        format.html { redirect_to @abstract_doc, notice: 'Abstract doc was successfully created.' }
        format.json { render :show, status: :created, location: @abstract_doc }
      else
        format.html { render :new }
        format.json { render json: @abstract_doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abstract_docs/1
  # PATCH/PUT /abstract_docs/1.json
  def update
    respond_to do |format|
      if @abstract_doc.update(abstract_doc_params)
        format.html { redirect_to @abstract_doc, notice: 'Abstract doc was successfully updated.' }
        format.json { render :show, status: :ok, location: @abstract_doc }
      else
        format.html { render :edit }
        format.json { render json: @abstract_doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abstract_docs/1
  # DELETE /abstract_docs/1.json
  # def destroy
  #   @abstract_doc.destroy
  #   respond_to do |format|
  #     format.html { redirect_to abstract_docs_url, notice: 'Abstract doc was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private

    def authenticate_viewer
      unless (@abstract_doc.reviewers + [@abstract_doc.user]).include?(current_user)
        redirect_to root_url
      end
    end

    def authenticate_editor
      redirect_to root_url unless @abstract_doc.user == current_user
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_abstract_doc
      @abstract_doc = AbstractDoc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def abstract_doc_params
      params.require(:abstract_doc).permit(:title, :attachment, :category_id, :status)
    end
end

app/helpers/abstract_docs_helper.rb
module AbstractDocsHelper
end

app/views/abstract_docs/_form.html.erb
<%= form_for(@abstract_doc, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @abstract_doc.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@abstract_doc.errors.count, "error") %> prohibited this abstract_doc from being saved:</h4>

      <ul>
      <% @abstract_doc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :attachment, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :attachment %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :category, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select(:category_id, Category.all, :id, :name, value:1, class: "form-control" )%>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :status, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select(:status, AbstractDoc.statuses.for_select[0..1], :second, :first, value:1, class: "form-control" )%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/abstract_docs/edit.html.erb
<div class="page-header">
  <%= link_to abstract_docs_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @abstract_doc, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing Abstract</h1>
</div>

<%= render 'form' %>

app/views/abstract_docs/index.html.erb
<%= content_for(:title, @title || '') %>

<div class="page-header">
  <%= link_to new_abstract_doc_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Abstract
  <% end %>
  <h1>Listing Abstracts</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Attachment</th>
            <th>Category</th>
            <th>User</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @abstract_docs) do |abstract_doc| %>
            <td><%= abstract_doc.title %></td>
            <td><%= link_to abstract_doc.attachment_url, abstract_doc.attachment_url %></td>
            <td><%= link_to abstract_doc.category.name %></td>
            <td><%= abstract_doc.user.name %></td>
            <td><%= link_to 'Show', abstract_doc %></td>
        <td><%= link_to 'Edit', edit_abstract_doc_path(abstract_doc) %></td>
        <td><%= link_to 'Destroy', abstract_doc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/abstract_docs/new.html.erb
<div class="page-header">
  <%= link_to abstract_docs_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Abstract</h1>
</div>

<%= render 'form' %>

app/views/abstract_docs/show.html.erb
<div class="page-header">
  <%= link_to abstract_docs_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_abstract_doc_path(@abstract_doc), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show Abstract</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @abstract_doc.title %></dd>

  <dt>Attachment:</dt>
  <dd><%= link_to @abstract_doc.attachment_url, @abstract_doc.attachment_url %></dd>

  <dt>Category:</dt>
  <dd><%= @abstract_doc.category.name %></dd>

  <dt>User:</dt>
  <dd><%= @abstract_doc.user.name %></dd>

</dl>