config/routes.rb
Rails.application.routes.draw do
  resources :open_studios, :only => [:show, :new, :create]
  resources :open_houses, :only => [:show, :new, :create]
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :reviews, :except => [:destroy, :new, :create]
  resources :categories, :only => [:show]
  resources :abstract_docs, :except => [:destroy, :index]
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


  get "abstract" => "pages#abstract"
  get ":slug" => "pages#show", :as => 'page'

  root "pages#show", slug: "home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/open_studio.rb
class OpenStudio < ApplicationRecord
  after_save do
    NotificationsMailer.open_studio_ack(self).deliver_now
  end
end

app/controllers/open_studios_controller.rb
class OpenStudiosController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create, :show]
  before_action :set_open_studio, only: [:show, :edit, :update, :destroy]

  # GET /open_studios
  # GET /open_studios.json
  # def index
  #   @open_studios = OpenStudio.all
  # end

  # GET /open_studios/1
  # GET /open_studios/1.json
  def show
  end

  # GET /open_studios/new
  def new
    @open_studio = OpenStudio.new
  end

  # GET /open_studios/1/edit
  # def edit
  # end

  # POST /open_studios
  # POST /open_studios.json
  def create
    @open_studio = OpenStudio.new(open_studio_params)

    respond_to do |format|
      if @open_studio.save
        format.html { redirect_to @open_studio, notice: 'Open studio was successfully created.' }
        format.json { render :show, status: :created, location: @open_studio }
      else
        format.html { render :new }
        format.json { render json: @open_studio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /open_studios/1
  # PATCH/PUT /open_studios/1.json
  # def update
  #   respond_to do |format|
  #     if @open_studio.update(open_studio_params)
  #       format.html { redirect_to @open_studio, notice: 'Open studio was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @open_studio }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @open_studio.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /open_studios/1
  # DELETE /open_studios/1.json
  # def destroy
  #   @open_studio.destroy
  #   respond_to do |format|
  #     format.html { redirect_to open_studios_url, notice: 'Open studio was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_open_studio
      @open_studio = OpenStudio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def open_studio_params
      params.require(:open_studio).permit(:name, :affiliation, :interested_in, :email)
    end
end

app/helpers/open_studios_helper.rb
module OpenStudiosHelper
end

app/views/open_studios/_form.html.erb
<%= form_for(@open_studio, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @open_studio.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@open_studio.errors.count, "error") %> prohibited this open_studio from being saved:</h4>

      <ul>
      <% @open_studio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :affiliation, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :affiliation, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :interested_in, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :interested_in, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Register", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/open_studios/edit.html.erb
<div class="page-header">
  <%= link_to open_studios_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @open_studio, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing open_studio</h1>
</div>

<%= render 'form' %>

app/views/open_studios/index.html.erb
<div class="page-header">
  <%= link_to new_open_studio_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Open studio
  <% end %>
  <h1>Listing open_studios</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Affiliation</th>
            <th>Interested in</th>
            <th>Email</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @open_studios) do |open_studio| %>
            <td><%= open_studio.name %></td>
            <td><%= open_studio.affiliation %></td>
            <td><%= open_studio.interested_in %></td>
            <td><%= open_studio.email %></td>
            <td><%= link_to 'Show', open_studio %></td>
        <td><%= link_to 'Edit', edit_open_studio_path(open_studio) %></td>
        <td><%= link_to 'Destroy', open_studio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/open_studios/new.html.erb
<div class="page-header">
  <h1>Registration for Open Studio</h1>
</div>

<%= render 'form' %>

app/views/open_studios/show.html.erb
<div class="page-header">
  <h1>Your Registration details for Open House</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @open_studio.name %></dd>

  <dt>Affiliation:</dt>
  <dd><%= @open_studio.affiliation %></dd>

  <dt>Interested in:</dt>
  <dd><%= @open_studio.interested_in %></dd>

  <dt>Email:</dt>
  <dd><%= @open_studio.email %></dd>

</dl>