config/routes.rb
Rails.application.routes.draw do
  resources :open_studios, :only => [:show, :new, :create]
  resources :open_houses, :only => [:show, :new, :create]
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :reviews, :except => [:destroy, :new, :create]
  resources :categories, :only => [:show]
  resources :abstract_docs, :except => [:destroy, :index]
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


  get "abstract" => "pages#abstract"
  get ":slug" => "pages#show", :as => 'page'

  root "pages#show", slug: "home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_editor, only: [:edit, :update]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = current_user.reviews
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  # def new
  #   @review = Review.new
  # end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  # def create
  #   @review = Review.new(review_params)
  #
  #   respond_to do |format|
  #     if @review.save
  #       format.html { redirect_to @review, notice: 'Review was successfully created.' }
  #       format.json { render :show, status: :created, location: @review }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @review.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  # def destroy
  #   @review.destroy
  #   respond_to do |format|
  #     format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    def authenticate_editor
      redirect_to root_url unless @review.user == current_user
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:user_id, :abstract_doc_id, :originality, :expand, :impact, :methods, :clarity, :comments, :status, :attachment)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @review.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <dl class="dl-horizontal">
    <dt>Title:</dt>
    <dd><%= @review.abstract_doc.title %></dd>

    <dt>Attachment:</dt>
    <dd><%= link_to @review.abstract_doc.attachment_url, @review.abstract_doc.attachment_url %></dd>

    <dt>Category:</dt>
    <dd><%= @review.abstract_doc.category.name %></dd>

    <dt>User:</dt>
    <dd><%= @review.abstract_doc.user.name %></dd>
  </dl>

  <div class="form-group">
    <%= f.label "Originality of the submission", class: "col-sm-6 control-label" %>
    <div class="col-sm-6">
      <%= f.number_field :originality, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Does the submission help to expand or further research in this subject area?", class: "col-sm-6 control-label" %>
    <div class="col-sm-6">
      <%= f.number_field :expand, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Rate the significance and potential impact of the idea in the abstract is high or low (on a scale of 5)", class: "col-sm-6 control-label" %>
    <div class="col-sm-6">
      <%= f.number_field :impact, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Rate the Methods and Means adapted (on a scale of 5)", class: "col-sm-6 control-label" %>
    <div class="col-sm-6">
      <%= f.number_field :methods, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Clarity of Writing", class: "col-sm-6 control-label" %>
    <div class="col-sm-6">
      <%= f.number_field :clarity, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Any important suggestions or Critique on the idea presented for its further improvement, along with Comments on points 1-5 above.", class: "col-sm-12" %>
    <div class="col-sm-12">
      <%= f.cktext_area :comments, ckeditor: { language: 'uk'}, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :attachment, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :attachment %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :status, class: "col-sm-6 control-label" %>
    <div class="col-sm-6">
      <%= f.collection_select(:status, AbstractDoc.statuses.for_select[0..1], :second, :first, value: 0, class: "form-control" )%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-10 col-sm-2">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<div class="page-header">
  <%= link_to reviews_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @review, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Review for <%= @review.abstract_doc.title %></h1>
</div>

<%= render 'form' %>

app/views/reviews/index.html.erb
<div class="page-header">
  <h1>Listing reviews</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Abstract doc</th>
            <th>Originality</th>
            <th>Expand</th>
            <th>Impact</th>
            <th>Methods</th>
            <th>Clarity</th>
            <th>Comments</th>
            <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @reviews) do |review| %>
            <td><%= link_to review.abstract_doc.title, edit_review_path(review) %></td>
            <td><%= review.originality %></td>
            <td><%= review.expand %></td>
            <td><%= review.impact %></td>
            <td><%= review.methods %></td>
            <td><%= review.clarity %></td>
            <td><%== review.comments %></td>
            <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reviews/new.html.erb
<div class="page-header">
  <%= link_to reviews_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New review</h1>
</div>

<%= render 'form' %>

app/views/reviews/show.html.erb
<div class="page-header">
  <%= link_to reviews_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_review_path(@review), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show review</h1>
</div>

<dl class="dl-horizontal">
  <dt>User:</dt>
  <dd><%= @review.user %></dd>

  <dt>Abstract doc:</dt>
  <dd><%= @review.abstract_doc %></dd>

  <dt>Originality:</dt>
  <dd><%= @review.originality %></dd>

  <dt>Expand:</dt>
  <dd><%= @review.expand %></dd>

  <dt>Impact:</dt>
  <dd><%= @review.impact %></dd>

  <dt>Methods:</dt>
  <dd><%= @review.methods %></dd>

  <dt>Clarity:</dt>
  <dd><%= @review.clarity %></dd>

  <dt>Comments:</dt>
  <dd><%= @review.comments %></dd>

  <dt>Attachment:</dt>
  <dd><%= link_to @review.attachment_url, @review.attachment_url %></dd>


</dl>